### ISSUE TITLE
Chararacterize minimum signal requirements

### ISSUE THREAD

**Issue by ckuethe** [wnagele/gr-adsb#3]
I'll probably send a PR to close this later tonight - gonna go hang out at the airport for a little while with 4 different receivers, a couple of antennas, ... - just as soon as I get some test measurements and recordings.

Sample rate, bandwidth, SNR ...

**Comment by wnagele** [comment]
Cool stuff. I haven't done any actual comparison but I would expect at least dump1090 to perform better as they have a bunch of phase enhancing, error correction, etc. code in there.

Especially the values used to shift the signal down and amplify it's magnitude could be experimented with to see if there are better values for it.

**Comment by wnagele** [comment]
Maybe another time ;)
