### ISSUE TITLE
error decoding speed

### ISSUE THREAD

**Issue by ckuethe** [wnagele/gr-adsb#4]
note that I have parity checking turned off...

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/gnuradio/lib/python2.7/dist-packages/adsb/decoder.py", line 52, in run
    self.decode(self.rx_msgq.delete_head().to_string())
  File "/home/gnuradio/lib/python2.7/dist-packages/adsb/decoder.py", line 98, in decode
    speed_heading = get_speed_heading(decoded_msg)
  File "/home/gnuradio/lib/python2.7/dist-packages/adsb/decoder.py", line 280, in get_speed_heading
    v_ns_dir = bin2dec(msg[56])
IndexError: string index out of range

**Comment by wnagele** [comment]
Yep this can happen if parity checking is off. I'll think of a more elegant way to ignore parts that cannot be decoded so we don't loose the whole frame. Even if for instance the speed was bogus there could be correct data in the other parts of the frame still.

**Comment by ckuethe** [comment]
I suppose more of dump1090's magic can be ported over, such as the checksum brute-forcing. The intent here is to prevent the whole module from crashing if decoding fails. This doesn't protect against multi-bit errors that produce bogus data with valid checksums.

On that note, I think I should extend the output format to include a parity field; if you're running with parity checking turned off (idle curiousity or measurement of signal quality) this would allow you to log corrupted frames.
